---

env:
  node: true
  browser: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

plugins:
  - import

rules:
  no-console: 0
  import/no-unresolved: 0
  react/prop-types: 0

settings:
    react:
      version: detect
